language: go

go:
  - 1.4

services:
  - rabbitmq

install:
  - export PATH=${PATH}:${HOME}/gopath/bin
  - go get -v -t ./...
  - go get -v github.com/golang/lint/golint
  - go get -v golang.org/x/tools/cmd/vet

script:
  - go vet ./...
  - env
  - go test -v ./...
  - golint .
