language: go

go:
  - 1.x

install:
  - export PATH=${PATH}:${HOME}/gopath/bin
  - go get -v -t ./...
  - go get -v github.com/golang/lint/golint

before_script:
  - go vet ./...
  - golint .

script:
  - go test -v ./...
  - go test -v -test.race ./...
