language: go

go:
  - 1.6
  - 1.6.1
  - 1.6.2

services:
  - rabbitmq

env:
  - RABBIT_URL=amqp://guest:guest@localhost:5672

install:
  - export PATH=${PATH}:${HOME}/gopath/bin
  - go get -v -t ./...
  - go get -v github.com/golang/lint/golint

before_script:
  - go vet ./...
  - golint .

script:
  - go test -v ./...
  - go test -v -test.race ./...
